---
default: --profile html_report --profile chrome --tags ~@wip
html_report: --format progress --format html --out=reports/features_report.html
dev: --tags @wip --profile headless
chrome: --tags ~@wip browser=chrome
ie: --tags ~@wip browser=ie
firefox: --tags ~@wip browser=firefox
headless: --tags ~@wip browser=phantomjs